version: '3'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    # command: "/opt/mssql/bin/mssql-conf set sqlagent.enabled true && echo 'enable sqlagent' && /opt/mssql/bin/sqlservr"
    command: /agent.sh
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: Developer
      SA_PASSWORD: P@ssw0rd
    volumes:
      - ./agent.sh:/agent.sh
    ports:
      - 51433:1433
    networks:
      - test-kpt

  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:sqlserver://mssql:1433;databaseName=master -schemas=flyway -user=sa -password=P@ssw0rd -connectRetries=60 migrate
    environment:
      - FLYWAY_EDITION=community
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - mssql
    networks:
      - test-kpt


networks:
  test-kpt:
    external: true