/**
 * Kettle-Project-Toolbox project archive deploy pipeline script
 *
 * Created by xiaoyao9184 on 2020/5/15.
 *
 * It will add find_kpt_project and kpt_project_deploy and run it.
 * Only master run find_kpt_project, 
 * Only master will run 'Project jobs' stage in kpt_project_deploy
 *
 * It also add trigger_${env.JOB_NAME} free-style job for trigger this job,
 * Because fstrigger cant use with pipeline job,
 * ee https://issues.jenkins-ci.org/browse/JENKINS-48239
 *
 *
 * Plugin dependencies
 * - job-dsl
 * - pipeline-utility-steps
 * - fstrigger
 * - workflow-multibranch
 * Disable script security for Job DSL (run as the specified admin user cant run find_kpt_project).
 * Or run as the specified admin user with script approval if need
 *
 * Pipeline script dependencies
 * - find_kpt_project
 * - kpt_project_deploy
 * In 'jenkins/' directory with same repository of this script 
 *
 */
pipeline {
    agent {
        node {
            //cant run on other node, because FolderContentTrigger need ArchivePath
            label "${params.Node}"
        }
    }
    parameters {
        //only this job
        booleanParam(
            name: 'CreateTrigger',
            defaultValue: true,
            description: 'for trigger job')
            
        //for all
        string(
            name: 'Node',
            defaultValue: 'master',
            description: 'Node label or node name for run')
        string(
            name: 'WorkPath_On_Windows', 
            defaultValue: '', 
            description: """jenkins job work directory, 
                for fix cant cross-device hard link when 
                jenkins run in docker default workspace and PDI path with different mount.""")
        string(
            name: 'WorkPath_On_Unix', 
            defaultValue: '', 
            description: """jenkins job work directory, 
                for fix cant cross-device hard link when 
                jenkins run in docker default workspace and PDI path with different mount.""")
        
        //Pass to all child job
        string(
            name: 'ProjectName', 
            defaultValue: 'default', 
            description: 'project name!')

        string(
            name: 'PDIURL', 
            defaultValue: 'https://jaist.dl.sourceforge.net/project/pentaho/Data%20Integration/7.1/pdi-ce-7.1.0.0-12.zip', 
            description: 'The PDI URL!')
        string(
            name: 'PDIPath_On_Windows', 
            defaultValue: 'D:\\Program\\Kettle\\pdi-ce-7.1.0.0-12\\data-integration', 
            description: 'data-integration directory')
        string(
            name: 'PDIPath_On_Unix', 
            defaultValue: '/home/jenkins/kettle/pdi-ce-7.1.0.0-12/data-integration', 
            description: 'data-integration directory')
            
        string(
            name: 'KPTURL', 
            defaultValue: 'https://github.com/xiaoyao9184/Kettle-Project-Toolbox.git', 
            description: 'The KPT git url!')
        string(
            name: 'KPTPath_On_Windows', 
            defaultValue: 'D:\\Program\\Kettle\\Kettle-Project-Toolbox', 
            description: 'Kettle-Project-Toolbox directory')
        string(
            name: 'KPTPath_On_Unix', 
            defaultValue: '/home/jenkins/kettle/kettle-project-toolbox', 
            description: 'Kettle-Project-Toolbox directory')
        
        //Pass to build job
        string(
            name: 'ArchivePath_On_Windows', 
            defaultValue: 'D:\\Archive', 
            description: 'archive directory!')
        string(
            name: 'ArchivePath_On_Unix', 
            defaultValue: '/home/jenkins/archive', 
            description: 'archive directory!')
        
        //Pass to deploy job
        string(
            name: 'DeployProfile', 
            defaultValue: 'prod', 
            description: 'active profile!')
        string(
            name: 'DeployPath_On_Windows', 
            defaultValue: 'D:\\Program\\ETL\\Prod_Profile', 
            description: 'project directory!')
        string(
            name: 'DeployPath_On_Unix', 
            defaultValue: '/home/jenkins/etl/prod_profile', 
            description: 'project directory!')
    }
    options {
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }
    stages {

        // stage('Config job trigger') {
        //     steps {
        //         script {
        //             def path = null;
        //             if (isUnix()) {
        //                 path = "${params.ArchivePath_On_Unix}/${params.ProjectName}"
        //             } else {
        //                 path = "${params.ArchivePath_On_Windows}\\${params.ProjectName}"
        //             }
        //             properties(
        //                 [
        //                     pipelineTriggers([[
        //                         $class: 'FolderContentTrigger', 
        //                         cronTabSpec: 'H 0 * * *',
        //                         path: "${path}",
        //                         includes: "*.zip",
        //                         excludeCheckLastModificationDate: false,
        //                         excludeCheckContent: false,
        //                         excludeCheckFewerOrMoreFiles: false
        //                     ]])
        //                 ]
        //             )
        //         }
        //     }
        // }

        stage("Add trigger job") {
            when {
                expression { params.CreateTrigger } 
            }
            steps {
                script {
                    ProjectArchivePath = null;
                    if (isUnix()) {
                        ProjectArchivePath = "${params.ArchivePath_On_Unix}/${params.ProjectName}"
                    } else {
                        ProjectArchivePath = "${params.ArchivePath_On_Windows}\\${params.ProjectName}"
                        ProjectArchivePath = ProjectArchivePath.replaceAll('\\\\','/')
                    }
                    SimpleJobName = "${env.JOB_NAME}".tokenize('/').last()
                }
                jobDsl(
                    scriptText: """
                    freeStyleJob("${SimpleJobName}(trigger)") {
                        configure { node ->
                            node / 'triggers' << 'org.jenkinsci.plugins.fstrigger.triggers.FolderContentTrigger' {
                                spec 'H/30 * * * *'
                                path '${ProjectArchivePath}'
                                includes '[Deploy]${params.ProjectName}*.zip'
                                excludeCheckLastModificationDate false
                                excludeCheckContent false
                                excludeCheckFewerOrMoreFiles false
                            }

                            node / 'builders' << 'hudson.plugins.parameterizedtrigger.TriggerBuilder' {
                                configs {
                                    'hudson.plugins.parameterizedtrigger.BlockableBuildTriggerConfig' {
                                        configs {
                                            'hudson.plugins.parameterizedtrigger.BooleanParameters' {
                                                configs {
                                                    'hudson.plugins.parameterizedtrigger.BooleanParameterConfig' {
                                                        name 'CreateTrigger'
                                                        value 'false'
                                                    }
                                                }
                                            }
                                        }
                                        projects '${SimpleJobName}'
                                        condition 'ALWAYS'
                                        triggerWithNoParameters 'false'
                                        triggerFromChildProjects 'false'
                                        block {
                                            buildStepFailureThreshold {
                                                name FAILURE
                                                ordinal 2
                                                color RED
                                                completeBuild true
                                            }
                                            unstableThreshold {
                                                name UNSTABLE
                                                ordinal 1
                                                color YELLOW
                                                completeBuild true
                                            }
                                            failureThreshold {
                                                name FAILURE
                                                ordinal 2
                                                color RED
                                                completeBuild true
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    """, 
                    removedJobAction: 'IGNORE', 
                    lookupStrategy: 'SEED_JOB',
                    sandbox: true
                )
            }
        }

        stage('Add find_kpt_project kpt_project_deploy kpt_project_job') {
            steps {
                script {
                    echo "get scm"
                    try {
                        scmUrl = scm.getUserRemoteConfigs()[0].getUrl()
                        credentialsId = scm.getUserRemoteConfigs()[0].getCredentialsId()
                        branch = scm.branches[0].name
                    } catch(Exception ex) {
                        println("Cant access scm, use KPT on github!")
                        scmUrl = "${params.KPTURL}"
                        credentialsId = ''
                        branch = '*/master'
                    }
                    echo "Will use '${credentialsId}' check ${branch} @ ${scmUrl} for pipeline job"
                }
                echo 'Add find_kpt_project job...'
                jobDsl(
                    scriptText: """
                    pipelineJob("find_kpt_project") {
                        parameters {
                            stringParam('Node', '')
                            stringParam('WorkPath_On_Windows', '')
                            stringParam('WorkPath_On_Unix', '')
                            stringParam('ProjectName', "${params.ProjectName}")

                            stringParam('ArchivePath_On_Windows', '')
                            stringParam('ArchivePath_On_Unix', '')
                        }
                        definition {
                            cpsScm {
                                scm {
                                    git { 
                                        remote {
                                            credentials("${credentialsId}")
                                            url("${scmUrl}")
                                        }
                                        branch("${branch}")
                                    }
                                }
                                scriptPath("jenkins/find_kpt_project.jenkinsfile")
                                lightweight(true)
                            }
                        }
                    }
                    """, 
                    removedJobAction: 'IGNORE', 
                    lookupStrategy: 'SEED_JOB',
                    sandbox: true
                )
                
                echo 'Add kpt_project_deploy job...'
                jobDsl(
                    scriptText: """
                    pipelineJob("kpt_project_deploy") {
                        parameters {
                            stringParam('Node', '')
                            stringParam('WorkPath_On_Windows', '')
                            stringParam('WorkPath_On_Unix', '')
                            stringParam('ProjectName', "${params.ProjectName}")
                            
                            stringParam('PDIURL', "${params.PDIURL}")
                            stringParam('PDIPath_On_Windows', '')
                            stringParam('PDIPath_On_Unix', '')

                            stringParam('KPTURL', "${params.KPTURL}")
                            stringParam('KPTPath_On_Windows', '')
                            stringParam('KPTPath_On_Unix', '')

                            stringParam('ArchiveProject', "find_kpt_project")

                            stringParam('DeployProfile', "${params.DeployProfile}")
                            stringParam('DeployPath_On_Windows', '')
                            stringParam('DeployPath_On_Unix', '')
                        }
                        definition {
                            cpsScm {
                                scm {
                                    git { 
                                        remote {
                                            credentials("${credentialsId}")
                                            url("${scmUrl}")
                                        }
                                        branch("${branch}")
                                    }
                                }
                                scriptPath("jenkins/kpt_project_deploy.jenkinsfile")
                                lightweight(true)
                            }
                        }
                    }
                    """, 
                    removedJobAction: 'IGNORE', 
                    lookupStrategy: 'SEED_JOB',
                    sandbox: true
                )
                
                echo 'Add kpt_project_job job...'
                jobDsl(
                    scriptText: """
                    pipelineJob("kpt_project_job") {
                        parameters {
                            stringParam('WorkPath_On_Windows', '')
                            stringParam('WorkPath_On_Unix', '')
                            stringParam('ProjectName', "${params.ProjectName}")
                            
                            stringParam('KPTPath_On_Windows', '')
                            stringParam('KPTPath_On_Unix', '')

                            stringParam('ArchiveProject', "find_kpt_project")

                            stringParam('DeployProfile', "${params.DeployProfile}")
                            stringParam('DeployPath_On_Windows', '')
                            stringParam('DeployPath_On_Unix', '')
                        }
                        definition {
                            cpsScm {
                                scm {
                                    git { 
                                        remote {
                                            credentials("${credentialsId}")
                                            url("${scmUrl}")
                                        }
                                        branch("${branch}")
                                    }
                                }
                                scriptPath("jenkins/kpt_project_job.jenkinsfile")
                                lightweight(true)
                            }
                        }
                    }
                    """, 
                    removedJobAction: 'IGNORE', 
                    lookupStrategy: 'SEED_JOB',
                    sandbox: true
                )
            }
        }

        stage('Run find_kpt_project') {
            steps {
                echo 'Run find_kpt_project job on master node...'
                script {
                    build job: 'find_kpt_project', 
                        parameters: [
                            string(name: 'Node', value: "master"),
                            string(name: 'WorkPath_On_Windows', value: "${params.WorkPath_On_Windows}"),
                            string(name: 'WorkPath_On_Unix', value: "${params.WorkPath_On_Unix}"),
                            string(name: 'ProjectName', value: "${params.ProjectName}"),

                            string(name: 'ArchivePath_On_Windows', value: "${params.ArchivePath_On_Windows}"),
                            string(name: 'ArchivePath_On_Unix', value: "${params.ArchivePath_On_Unix}")
                        ], 
                        wait: true,
                        //Will not be deployed by this terminal 
                        propagate: false
                }
            }
        }

        stage('Run kpt_project_deploy') {
            steps {
                echo 'Run kpt_project_deploy job on all etl nodes...'
                script {
                    def kpt_project_deploy_jobs = [:]
                    def etlNodes = nodesByLabel label: 'etl', offline: false
                    if(etlNodes.size() == 0){
                        etlNodes.add('master')
                    }
                    for(i = 0; i < etlNodes.size(); i++) {
                        def agentName = etlNodes[i]
                        if (agentName == ''){
                            agentName = 'master'
                        }
                        if (agentName != null) {
                            println "Prearing task for " + agentName

                            kpt_project_deploy_jobs["run_on_node_${agentName}"] = {
                            stage("Run on node[${agentName}]") {
                                echo "run on agent: ${agentName}"

                                build job: 'kpt_project_deploy', 
                                    parameters: [
                                        string(name: 'Node', value: "${agentName}"),
                                        string(name: 'WorkPath_On_Windows', value: "${params.WorkPath_On_Windows}"),
                                        string(name: 'WorkPath_On_Unix', value: "${params.WorkPath_On_Unix}"),
                                        string(name: 'ProjectName', value: "${params.ProjectName}"),
                                        
                                        string(name: 'PDIURL', value: "${params.PDIURL}"),
                                        string(name: 'PDIPath_On_Windows', value: "${params.PDIPath_On_Windows}"),
                                        string(name: 'PDIPath_On_Unix', value: "${params.PDIPath_On_Unix}"),

                                        string(name: 'KPTURL', value: "${params.KPTURL}"),
                                        string(name: 'KPTPath_On_Windows', value: "${params.KPTPath_On_Windows}"),
                                        string(name: 'KPTPath_On_Unix', value: "${params.KPTPath_On_Unix}"),

                                        string(name: 'ArchiveProject', value: "find_kpt_project"),

                                        string(name: 'DeployProfile', value: "${params.DeployProfile}"),
                                        string(name: 'DeployPath_On_Windows', value: "${params.DeployPath_On_Windows}"),
                                        string(name: 'DeployPath_On_Unix', value: "${params.DeployPath_On_Unix}")
                                    ], 
                                    wait: true
                            }}
                        }
                    }
                    parallel kpt_project_deploy_jobs
                }
            }
        }

        stage('Run kpt_project_job') {
            steps {
                echo 'Run kpt_project_job job on master node...'
                script {
                    build job: 'kpt_project_job', 
                        parameters: [
                            string(name: 'WorkPath_On_Windows', value: "${params.WorkPath_On_Windows}"),
                            string(name: 'WorkPath_On_Unix', value: "${params.WorkPath_On_Unix}"),
                            string(name: 'ProjectName', value: "${params.ProjectName}"),

                            string(name: 'KPTPath_On_Windows', value: "${params.KPTPath_On_Windows}"),
                            string(name: 'KPTPath_On_Unix', value: "${params.KPTPath_On_Unix}"),

                            string(name: 'ArchiveProject', value: "find_kpt_project"),

                            string(name: 'DeployProfile', value: "${params.DeployProfile}"),
                            string(name: 'DeployPath_On_Windows', value: "${params.DeployPath_On_Windows}"),
                            string(name: 'DeployPath_On_Unix', value: "${params.DeployPath_On_Unix}")
                        ], 
                        wait: true
                }
            }
        }
    }
}
