version: '3'
services:

  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://mysql -schemas=flyway-canal -user=root -password=P@ssw0rd -connectRetries=60 migrate
    environment:
      - FLYWAY_EDITION=community
    volumes:
      - ./sql:/flyway/sql
    networks:
      - test-kpt

  canal-admin:
    image: canal/canal-admin:v1.1.5
    environment:
      - server.port=8089
      - canal.adminUser=admin
      - canal.adminPasswd=admin
      - spring.datasource.address=mysql:3306
      - spring.datasource.database=canal_manager
      - spring.datasource.username=root
      - spring.datasource.password=kpt.123
    ports:
      - "58089:8089"
    networks:
      - test-kpt
    depends_on:
      - flyway

  canal-server:
    image: canal/canal-server:v1.1.5
    environment:
      - canal.register.ip=0.0.0.0
      - canal.register.ip=canal-server
      - canal.admin.manager=canal-admin:8089
      - canal.admin.user=admin
      - canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441
      - canal.admin.port=11110
      - canal.admin.register.auto=true
      - canal.admin.register.cluster=default
    ports: 
      - "11110:11110"
      - "11111:11111"
      - "11112:11112"
      - "9100:9100"
    networks:
      - test-kpt
    depends_on:
      - canal-admin


networks:
  test-kpt:
    external: true