/**
 * Kettle-Project-Toolbox project source code build pipeline script
 *
 * Created by xiaoyao9184 on 2020/5/15.
 *
 * It will add build_kpt_project and deploy_kpt_project and run it.
 * Only master run build_kpt_project, 
 * Only master will run 'Project jobs' stage in deploy_kpt_project
 *
 *
 * Plugin dependencies
 * - job-dsl
 * Disable script security for Job DSL (run as the specified admin user cant run build_kpt_project).
 * Or run as the specified admin user with script approval if need
 *
 * Pipeline script dependencies
 * - build_kpt_project
 * - deploy_kpt_project
 * In 'jenkins/' directory with same repository of this script 
 *
 */
pipeline {
    agent {
        node {
            label "${params.Node}"
        }
    }
    parameters {
        string(
            name: 'Node',
            defaultValue: 'master',
            description: 'Node label or node name for run')
        string(
            name: 'WorkPath_On_Windows', 
            defaultValue: '', 
            description: """jenkins job work directory, 
                for fix cant cross-device hard link when 
                jenkins run in docker default workspace and PDI path with different mount.""")
        string(
            name: 'WorkPath_On_Unix', 
            defaultValue: '', 
            description: """jenkins job work directory, 
                for fix cant cross-device hard link when 
                jenkins run in docker default workspace and PDI path with different mount.""")
        
        //Pass to all child job
        string(
            name: 'ProjectName', 
            defaultValue: 'default', 
            description: 'project name!')
        
        string(
            name: 'PDIURL', 
            defaultValue: 'https://jaist.dl.sourceforge.net/project/pentaho/Data%20Integration/7.1/pdi-ce-7.1.0.0-12.zip', 
            description: 'The PDI URL!')
        string(
            name: 'PDIPath_On_Windows', 
            defaultValue: 'D:\\Program\\Kettle\\data-integration', 
            description: 'data-integration directory')
        string(
            name: 'PDIPath_On_Unix', 
            defaultValue: '/home/jenkins/kettle/data-integration', 
            description: 'data-integration directory')
        
        string(
            name: 'KPTURL', 
            defaultValue: 'https://github.com/xiaoyao9184/Kettle-Project-Toolbox.git', 
            description: 'The KPT git url!')
        string(
            name: 'KPTPath_On_Windows', 
            defaultValue: 'D:\\Program\\Kettle\\Kettle-Project-Toolbox', 
            description: 'Kettle-Project-Toolbox directory')
        string(
            name: 'KPTPath_On_Unix', 
            defaultValue: '/home/jenkins/kettle/kettle-project-toolbox', 
            description: 'Kettle-Project-Toolbox directory')
        
        //Pass to build job
        string(
            name: 'ArchivePath_On_Windows', 
            defaultValue: 'D:\\Archive', 
            description: 'archive directory!')
        string(
            name: 'ArchivePath_On_Unix', 
            defaultValue: '/home/jenkins/archive', 
            description: 'archive directory!')
        
        //Pass to deploy job
        string(
            name: 'DeployProfile', 
            defaultValue: 'dev', 
            description: 'active profile!')
        string(
            name: 'DeployPath_On_Windows', 
            defaultValue: 'D:\\Program\\ETL', 
            description: 'project directory!')
        string(
            name: 'DeployPath_On_Unix', 
            defaultValue: '/home/jenkins/etl/dev_profile', 
            description: 'project directory!')
    }
    options {
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }
    stages {

        stage('Add build_kpt_project deploy_kpt_project job') {
            steps {
                script {
                    scmUrl = scm.getUserRemoteConfigs()[0].getUrl()
                    credentialsId = scm.getUserRemoteConfigs()[0].getCredentialsId()
                    branch = scm.branches[0].name
                    echo "Will use ${credentialsId} check ${branch} @ ${scmUrl} for pipeline job"
                }
                echo 'Add build_kpt_project job...'
                jobDsl(
                    scriptText: """
                    pipelineJob("build_kpt_project") {
                        parameters {
                            stringParam('Node', "master")
                            stringParam('WorkPath_On_Windows', '')
                            stringParam('WorkPath_On_Unix', '')
                            stringParam('ProjectName', "${params.ProjectName}")

                            stringParam('PDIURL', "${params.PDIURL}")
                            stringParam('PDIPath_On_Windows', '')
                            stringParam('PDIPath_On_Unix', '')

                            stringParam('KPTURL', "${params.KPTURL}")
                            stringParam('KPTPath_On_Windows', '')
                            stringParam('KPTPath_On_Unix', '')

                            stringParam('ArchivePath_On_Windows', '')
                            stringParam('ArchivePath_On_Unix', '')

                            booleanParam('DeployFlow', false, 'use deploy_kpt_project for deploy')
                        }
                        definition {
                            cpsScm {
                                scm {
                                    git { 
                                        remote {
                                            credentials("${credentialsId}")
                                            url("${scmUrl}")
                                        }
                                        branch("${branch}")
                                    }
                                }
                                scriptPath("jenkins/build_kpt_project.jenkinsfile")
                                lightweight(true)
                            }
                        }
                    }
                    """, 
                    removedJobAction: 'IGNORE', 
                    lookupStrategy: 'SEED_JOB',
                    sandbox: true
                )
                
                echo 'Add deploy_kpt_project job...'
                jobDsl(
                    scriptText: """
                    pipelineJob("deploy_kpt_project") {
                        parameters {
                            stringParam('Node', "master")
                            stringParam('WorkPath_On_Windows', '')
                            stringParam('WorkPath_On_Unix', '')
                            stringParam('ProjectName', "${params.ProjectName}")
                            
                            stringParam('PDIURL', "${params.PDIURL}")
                            stringParam('PDIPath_On_Windows', '')
                            stringParam('PDIPath_On_Unix', '')

                            stringParam('KPTURL', "${params.KPTURL}")
                            stringParam('KPTPath_On_Windows', '')
                            stringParam('KPTPath_On_Unix', '')

                            stringParam('ArchiveProject', "build_kpt_project")

                            stringParam('DeployProfile', "${params.DeployProfile}")
                            stringParam('DeployPath_On_Windows', '')
                            stringParam('DeployPath_On_Unix', '')
                        }
                        definition {
                            cpsScm {
                                scm {
                                    git { 
                                        remote {
                                            credentials("${credentialsId}")
                                            url("${scmUrl}")
                                        }
                                        branch("${branch}")
                                    }
                                }
                                scriptPath("jenkins/deploy_kpt_project.jenkinsfile")
                                lightweight(true)
                            }
                        }
                    }
                    """, 
                    removedJobAction: 'IGNORE', 
                    lookupStrategy: 'SEED_JOB',
                    sandbox: true
                )
            }
        }

        stage('Run build_kpt_project job on master') {
            steps {
                echo 'Run build_kpt_project job...'
                script {
                    build job: 'build_kpt_project', 
                        parameters: [
                            string(name: 'Node', value: "master"),
                            string(name: 'WorkPath_On_Windows', value: "${params.WorkPath_On_Windows}"),
                            string(name: 'WorkPath_On_Unix', value: "${params.WorkPath_On_Unix}"),
                            string(name: 'ProjectName', value: "${params.ProjectName}"),

                            string(name: 'PDIURL', value: "${params.PDIURL}"),
                            string(name: 'PDIPath_On_Windows', value: "${params.PDIPath_On_Windows}"),
                            string(name: 'PDIPath_On_Unix', value: "${params.PDIPath_On_Unix}"),

                            string(name: 'KPTURL', value: "${params.KPTURL}"),
                            string(name: 'KPTPath_On_Windows', value: "${params.KPTPath_On_Windows}"),
                            string(name: 'KPTPath_On_Unix', value: "${params.KPTPath_On_Unix}"),

                            string(name: 'ArchivePath_On_Windows', value: "${params.ArchivePath_On_Windows}"),
                            string(name: 'ArchivePath_On_Unix', value: "${params.ArchivePath_On_Unix}")
                        ], 
                        wait: true
                }
            }
        }

        stage('Run deploy_kpt_project on all nodes') {
            steps {
                echo 'Run deploy_kpt_project job...'
                script {
                    def deploy_kpt_project_jobs = [:]
                    def etlNodes = nodesByLabel label: 'etl', offline: false
                    println etlNodes
                    for(i = 0; i < etlNodes.size(); i++) {
                        def agentName = etlNodes[i]
                        if (agentName == ''){
                            agentName = 'master'
                        }
                        if (agentName != null) {
                            println "Prearing task for " + agentName

                            deploy_kpt_project_jobs["run_on_node_${agentName}"] = {
                            stage("Run on node[${agentName}]") {
                                echo "run on agent: ${agentName}"

                                build job: 'deploy_kpt_project', 
                                    parameters: [
                                        string(name: 'Node', value: "${agentName}"),
                                        string(name: 'WorkPath_On_Windows', value: "${params.WorkPath_On_Windows}"),
                                        string(name: 'WorkPath_On_Unix', value: "${params.WorkPath_On_Unix}"),
                                        string(name: 'ProjectName', value: "${params.ProjectName}"),
                                        
                                        string(name: 'PDIURL', value: "${params.PDIURL}"),
                                        string(name: 'PDIPath_On_Windows', value: "${params.PDIPath_On_Windows}"),
                                        string(name: 'PDIPath_On_Unix', value: "${params.PDIPath_On_Unix}"),

                                        string(name: 'KPTURL', value: "${params.KPTURL}"),
                                        string(name: 'KPTPath_On_Windows', value: "${params.KPTPath_On_Windows}"),
                                        string(name: 'KPTPath_On_Unix', value: "${params.KPTPath_On_Unix}"),

                                        string(name: 'ArchiveProject', value: "build_kpt_project"),

                                        string(name: 'DeployProfile', value: "${params.DeployProfile}"),
                                        string(name: 'DeployPath_On_Windows', value: "${params.DeployPath_On_Windows}"),
                                        string(name: 'DeployPath_On_Unix', value: "${params.DeployPath_On_Unix}")
                                    ], 
                                    wait: true
                            }}
                        }
                    }
                    parallel deploy_kpt_project_jobs
                }
            }
        }
    }
    post {
        cleanup {
            deleteDir()
        }
    }
}
