version: "3.7"
services:
  mysql-time_connect:
    image: xiaoyao9184/kpt-cdc-to-rdb
    environment:
      PROFILE: test_kpt,debezium-mysql-pgsql
    volumes:
       - ./config.xml:/home/pentaho/kpt-cdc-to-rdb/config.xml