version: "3.7"
services:
  test:
    image: xiaoyao9184/kpt-kpt-cdc-to-rdb
    environment:
      PROFILE: prod,stream_all-cdc_event.mysql
    configs:
      - source: config.xml
        target: /home/pentaho/kpt-cdc-to-rdb/config.xml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
        window: 120s
    
configs:
  config.xml:
    file: ./config.xml