@ECHO OFF
SETLOCAL EnableDelayedExpansion

@REM variable equivalent to maitre option
@REM KPT_KETTLE__a
@REM KPT_KETTLE_SAFEMODE
@REM KPT_KETTLE__c
@REM KPT_KETTLE_CLUSTERED
@REM KPT_KETTLE__C
@REM KPT_KETTLE_CREATE__ENVIRONMENT
@REM KPT_KETTLE__d
@REM KPT_KETTLE_DONTWAIT
@REM KPT_KETTLE__e
@REM KPT_KETTLE_ENVIRONMENT
@REM KPT_KETTLE__f=
@REM KPT_KETTLE__z=
@REM KPT_KETTLE_FILE=
@REM KPT_KETTLE__g
@REM KPT_KETTLE_REMOTELOG
@REM KPT_KETTLE__h
@REM KPT_KETTLE_HELP
@REM KPT_KETTLE__I
@REM KPT_KETTLE_IMPORT__ENVIRONMENT=
@REM KPT_KETTLE__j
@REM KPT_KETTLE_JOB=
@REM KPT_KETTLE__i
@REM KPT_KETTLE_LEVEL=
@REM KPT_KETTLE__m
@REM KPT_KETTLE_METRICS=
@REM KPT_KETTLE__o
@REM KPT_KETTLE_PRINTOPTIONS=
@REM KPT_KETTLE__p
@REM KPT_KETTLE_PARAMETERS=
@REM KPT_KETTLE__p_
@REM KPT_KETTLE_PARAMETERS_=
@REM KPT_KETTLE__q
@REM KPT_KETTLE_QUERYDELAY=
@REM KPT_KETTLE__r
@REM KPT_KETTLE_RUNCONFIG=
@REM KPT_KETTLE__s
@REM KPT_KETTLE_SLAVE=
@REM KPT_KETTLE__t
@REM KPT_KETTLE_TRANSFORMATION=
@REM KPT_KETTLE__V
@REM KPT_KETTLE_ADD__VARIABLE__TO__ENVIRONMENT=
@REM KPT_KETTLE__x
@REM KPT_KETTLE_EXPORT=


SET current_script_dir=%~dp0
FOR %%F IN (%current_script_dir%.) DO SET parent_folder_dir=%%~dpF

SET KPT_COMMAND=maitre
SET KPT_KETTLE__a=" "
SET KPT_KETTLE_SAFEMODE=""
SET KPT_KETTLE__c=" "
SET KPT_KETTLE_CLUSTERED=" "
SET KPT_KETTLE__C=" "
SET KPT_KETTLE_CREATE__ENVIRONMENT=" "
SET KPT_KETTLE__d=" "
SET KPT_KETTLE_DONTWAIT=" "
SET KPT_KETTLE__e=" "
SET KPT_KETTLE_ENVIRONMENT=" "
SET KPT_KETTLE__f=" "
SET KPT_KETTLE__z=" "
SET KPT_KETTLE_FILE=" "
SET KPT_KETTLE__g=" "
SET KPT_KETTLE_REMOTELOG=" "
SET KPT_KETTLE__h=" "
SET KPT_KETTLE_HELP=" "
SET KPT_KETTLE__I=" "
SET KPT_KETTLE_IMPORT__ENVIRONMENT=" "
SET KPT_KETTLE__j=" "
SET KPT_KETTLE_JOB=" "
SET KPT_KETTLE__i=" "
SET KPT_KETTLE_LEVEL=" "
SET KPT_KETTLE__m=" "
SET KPT_KETTLE_METRICS=" "
SET KPT_KETTLE__o=" "
SET KPT_KETTLE_PRINTOPTIONS=" "
SET KPT_KETTLE__p=" "
SET KPT_KETTLE_PARAMETERS=" "
SET KPT_KETTLE__q=" "
SET KPT_KETTLE_QUERYDELAY=" "
SET KPT_KETTLE__r=" "
SET KPT_KETTLE_RUNCONFIG=" "
SET KPT_KETTLE__s=" "
SET KPT_KETTLE_SLAVE=" "
SET KPT_KETTLE__t=" "
SET KPT_KETTLE_TRANSFORMATION=" "
SET KPT_KETTLE__V=" "
SET KPT_KETTLE_ADD__VARIABLE__TO__ENVIRONMENT=" "
SET KPT_KETTLE__x=" "
SET KPT_KETTLE_EXPORT=" "

CALL %parent_folder_dir%KPT_RUN_COMMAND.bat
ECHO exit code will be 9


ECHO:
ECHO pause by %~nx0
PAUSE
