name: docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set git sha short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./canal-kafka-to-pgsql/Dockerfile
          push: true
          tags: xiaoyao9184/kpt-canal-kafka-to-pgsql:${{ steps.vars.outputs.sha_short }},xiaoyao9184/kpt-canal-kafka-to-pgsql:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
