name: cdc-to-rdb-docker

on:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: cdc
      - 
        name: Set git sha short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cdc-to-rdb/Dockerfile
          push: true
          tags: xiaoyao9184/kpt-cdc-to-rdb:${{ steps.vars.outputs.sha_short }},xiaoyao9184/kpt-cdc-to-rdb:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
